[tool.ruff]
select = [
    "E",
    "F",
#    "W"
]
ignore = ["E501"]
line-length = 100
exclude = [".git", "__pycache__", ".env", ".venv", "migrations", "tests"]
fix = false
[tool.ruff.per-file-ignores]
"tests/*.py" = ["F401"]  # Игнорировать F401 в тестовых файлах
"alembic/*" = ["F403", "F401"]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
asyncio_mode="auto"
asyncio_default_fixture_loop_scope="function"
filterwarnings="ignore"