"""edit Admin model

Revision ID: 094d447ab2b4
Revises: daacdfd30fa3
Create Date: 2024-12-05 08:27:27.238077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094d447ab2b4'
down_revision: Union[str, None] = 'daacdfd30fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('user_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'user_name')
    # ### end Alembic commands ###
