"""add colum viewed in Application

Revision ID: 17ac7cf41f33
Revises: 094d447ab2b4
Create Date: 2024-12-06 09:15:13.002747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ac7cf41f33'
down_revision: Union[str, None] = '094d447ab2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('viewed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'viewed')
    # ### end Alembic commands ###
