name: Test and Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      REDIS_URL: redis://localhost:6379/0
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_HOST: localhost
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      DATABASE_URL_TEST: postgresql+asyncpg://test_user:test_pass@localhost:5432/test_db
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for services to be ready
        run: |
          sudo apt-get install -y netcat
          while ! nc -z localhost 5432; do sleep 1; done
          while ! nc -z localhost 6379; do sleep 1; done

      - name: Run linters
        run: ruff check

      - name: Create logs directory
        run: mkdir -p $RUNNER_TEMP/logs
        env:
          LOGS_PATH: $RUNNER_TEMP/logs

      - name: Run tests
        run: pytest -v tests/
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_LOGS_TOKEN: ${{ secrets.TELEGRAM_LOGS_TOKEN }}
          TG_CHAT_ID_LOGS: ${{ secrets.TG_CHAT_ID_LOGS }}
          LOGS_PATH: $RUNNER_TEMP/logs
